name: Deploy to Github Pages
on:
  push: 
    branches: [ master ]
    
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.9.0
      with:        
        dotnet-version: 6.0.x
    
    - name: Publish .NET Core Project    
      run: dotnet publish ArchnemesisRecipies.csproj -c Release -o release -nologo
    
    - name: Change base-tag in index.html from / to ArchnemesisRecipies
      run: sed -i 's/<base href="\/" \/>/<base href="\/ArchnemesisRecipies\/" \/>/g' release/wwwroot/index.html
    
    - name: Change  service-worker.js path
      run: sed -i 's/service-worker.js/ArchnemesisRecipies\/service-worker.js/g' release/wwwroot/sw-registrator.js

    - name: Update service-worker version
      run: sed -i 's/{0}/${{ github.run_number }}/g' release/wwwroot/service-worker.js
    
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
    
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot    
